---
- name: Show Version
- hosts: all
  gather_facts: false
  connection: local
  
  vars:
    cli:
      username: admin
      password: LEcisc33e$
      timeout: 100
      
  tasks:
   - name: Verify ACL is present
     ios_command:
      provider: "{{ cli }}"
        - show switch

   - name: SAVE CONFIG
     ios_config:
       authorize: yes
       save: yes
