---
- name: cisco_sh_ver
  hosts: all
  gather_facts: false 
  tasks:
  - name: run show version on remote devices
    network_cli:
     commands:
     - show version       
  - name: show run on remote devices
    become: true
    cisco.ios.ios_command:
     commands: 
     - show run
